
spring:
  datasource:
    password: letmein
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLBDialect
      format_sql: true
    show-sql: true